openapi: 3.0.3
info:
  description: Endpoints usados por la app cliente de SuperEconomico con Supabase
    Auth y REST (PostgREST).
  title: SuperEconomico API Cliente
  version: 1.1.0
servers:
- description: Supabase Producción
  url: https://mvrlcbcydpubhovvrmvf.supabase.co
security:
- ApiKeyAuth: []
- BearerAuth: []
paths:
  /auth/v1/signup:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegistroRequest'
      responses:
        "200":
          description: Éxito
      summary: Crear cuenta de cliente
      tags:
      - Autenticación
      x-content-type: application/json
      x-accepts:
      - application/json
  /auth/v1/token:
    post:
      parameters:
      - explode: true
        in: query
        name: grant_type
        required: false
        schema:
          default: password
          type: string
        style: form
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/_auth_v1_token_post_request'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
          description: Éxito
      summary: Iniciar sesión (Login)
      tags:
      - Autenticación
      x-content-type: application/json
      x-accepts:
      - application/json
  /auth/v1/user:
    put:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/_auth_v1_user_put_request'
      responses:
        "200":
          description: Éxito
      summary: Actualizar contraseña
      tags:
      - Autenticación
      x-content-type: application/json
      x-accepts:
      - application/json
  /rest/v1/categorias:
    get:
      parameters:
      - explode: true
        in: query
        name: select
        required: false
        schema:
          default: '*'
          type: string
        style: form
      responses:
        "200":
          description: Lista de categorías
      summary: Listar categorías
      tags:
      - Catálogo
      x-accepts:
      - application/json
  /rest/v1/productos:
    get:
      parameters:
      - explode: true
        in: query
        name: select
        required: false
        schema:
          default: '*'
          type: string
        style: form
      - explode: true
        in: query
        name: categoria_id
        required: false
        schema:
          example: eq.1
          type: string
        style: form
      - explode: true
        in: query
        name: esta_activo
        required: false
        schema:
          default: eq.true
          type: string
        style: form
      responses:
        "200":
          description: Lista de productos
      summary: Listar productos (con filtros)
      tags:
      - Catálogo
      x-accepts:
      - application/json
  /rest/v1/perfiles:
    get:
      parameters:
      - explode: true
        in: query
        name: id
        required: false
        schema:
          example: eq.uuid
          type: string
        style: form
      - explode: true
        in: query
        name: telefono
        required: false
        schema:
          example: eq.95212400
          type: string
        style: form
      - explode: true
        in: query
        name: select
        required: false
        schema:
          default: '*'
          type: string
        style: form
      responses:
        "200":
          description: Datos del perfil
      summary: Buscar perfil (por ID o Teléfono)
      tags:
      - Perfiles
      x-accepts:
      - application/json
    patch:
      parameters:
      - explode: true
        in: query
        name: id
        required: false
        schema:
          example: eq.uuid
          type: string
        style: form
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Perfil'
      responses:
        "204":
          description: Actualizado correctamente
      summary: Actualizar información del perfil
      tags:
      - Perfiles
      x-content-type: application/json
      x-accepts:
      - application/json
  /rest/v1/pedidos:
    delete:
      parameters:
      - explode: true
        in: query
        name: id
        required: false
        schema:
          example: eq.1
          type: string
        style: form
      responses:
        "204":
          description: Eliminado
      summary: Eliminar un pedido
      tags:
      - Pedidos
      x-accepts:
      - application/json
    get:
      parameters:
      - explode: true
        in: query
        name: perfil_id
        required: false
        schema:
          example: eq.uuid
          type: string
        style: form
      - explode: true
        in: query
        name: order
        required: false
        schema:
          default: creado_at.desc
          type: string
        style: form
      responses:
        "200":
          description: Lista de pedidos
      summary: Historial de pedidos del usuario
      tags:
      - Pedidos
      x-accepts:
      - application/json
    post:
      parameters:
      - explode: false
        in: header
        name: Prefer
        required: false
        schema:
          default: return=representation
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Pedido'
      responses:
        "201":
          description: Creado
      summary: Crear encabezado de pedido
      tags:
      - Pedidos
      x-content-type: application/json
      x-accepts:
      - application/json
  /rest/v1/pedido_items:
    delete:
      parameters:
      - explode: true
        in: query
        name: id
        required: false
        schema:
          example: eq.1
          type: string
        style: form
      responses:
        "204":
          description: Eliminado
      summary: Quitar producto del pedido
      tags:
      - Pedidos
      x-accepts:
      - application/json
    get:
      parameters:
      - explode: true
        in: query
        name: pedido_id
        required: false
        schema:
          example: eq.1
          type: string
        style: form
      responses:
        "200":
          description: Detalles del pedido
      summary: Listar productos de un pedido
      tags:
      - Pedidos
      x-accepts:
      - application/json
    patch:
      parameters:
      - explode: true
        in: query
        name: id
        required: false
        schema:
          example: eq.1
          type: string
        style: form
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/_rest_v1_pedido_items_patch_request'
      responses:
        "204":
          description: Actualizado
      summary: Actualizar cantidad de un producto
      tags:
      - Pedidos
      x-content-type: application/json
      x-accepts:
      - application/json
    post:
      requestBody:
        content:
          application/json:
            schema:
              items:
                $ref: '#/components/schemas/PedidoItem'
              type: array
      responses:
        "201":
          description: Insertados
      summary: Insertar productos al pedido
      tags:
      - Pedidos
      x-content-type: application/json
      x-accepts:
      - application/json
  /rest/v1/direcciones:
    delete:
      parameters:
      - explode: true
        in: query
        name: id
        required: false
        schema:
          example: eq.1
          type: string
        style: form
      responses:
        "204":
          description: Eliminada
      summary: Eliminar dirección
      tags:
      - Direcciones
      x-accepts:
      - application/json
    get:
      parameters:
      - explode: true
        in: query
        name: perfil_id
        required: false
        schema:
          example: eq.uuid
          type: string
        style: form
      responses:
        "200":
          description: Lista de direcciones
      summary: Listar direcciones
      tags:
      - Direcciones
      x-accepts:
      - application/json
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Direccion'
      responses:
        "201":
          description: Creada
      summary: Agregar nueva dirección
      tags:
      - Direcciones
      x-content-type: application/json
      x-accepts:
      - application/json
components:
  schemas:
    RegistroRequest:
      example:
        password: "123456"
        data:
          nombre_completo: Juan Perez
          direcciones:
          - etiqueta: Casa
            latitud: 0.8008281904610115
            longitud: 6.027456183070403
            direccion: "Colonia Centro, casa 10"
          - etiqueta: Casa
            latitud: 0.8008281904610115
            longitud: 6.027456183070403
            direccion: "Colonia Centro, casa 10"
          telefono: "99999999"
        email: cliente@correo.com
      properties:
        email:
          example: cliente@correo.com
          type: string
        password:
          example: "123456"
          type: string
        data:
          $ref: '#/components/schemas/RegistroRequest_data'
      required:
      - data
      - email
      - password
      type: object
    DireccionRegistro:
      example:
        etiqueta: Casa
        latitud: 0.8008281904610115
        longitud: 6.027456183070403
        direccion: "Colonia Centro, casa 10"
      properties:
        etiqueta:
          example: Casa
          type: string
        direccion:
          example: "Colonia Centro, casa 10"
          type: string
        latitud:
          format: double
          type: number
        longitud:
          format: double
          type: number
      type: object
    AuthResponse:
      example:
        access_token: access_token
        user:
          id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          email: email
      properties:
        access_token:
          type: string
        user:
          $ref: '#/components/schemas/AuthResponse_user'
      type: object
    Categoria:
      properties:
        id:
          type: integer
        nombre:
          type: string
        imagen_url:
          type: string
      type: object
    Producto:
      properties:
        id:
          type: integer
        categoria_id:
          type: integer
        nombre:
          type: string
        descripcion:
          type: string
        precio:
          type: number
        imagen_url:
          type: string
        esta_activo:
          type: boolean
      type: object
    Pedido:
      example:
        creado_at: 2000-01-23T04:56:07.000+00:00
        estado: pendiente
        total: 6.027456183070403
        direccion_id: 1
        perfil_id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        id: 0
        metodo_pago: Efectivo
      properties:
        id:
          type: integer
        perfil_id:
          format: uuid
          type: string
        estado:
          enum:
          - pendiente
          - cocina
          - entrega
          - cerrado
          type: string
        total:
          type: number
        direccion_id:
          type: integer
        metodo_pago:
          example: Efectivo
          type: string
        creado_at:
          format: date-time
          type: string
      type: object
    PedidoItem:
      example:
        precio_unitario: 5.637376656633329
        producto_id: 1
        id: 0
        cantidad: 5
        pedido_id: 6
      properties:
        id:
          type: integer
        pedido_id:
          type: integer
        producto_id:
          type: integer
        cantidad:
          type: integer
        precio_unitario:
          type: number
      type: object
    Perfil:
      example:
        descripcion: descripcion
        nombre_completo: nombre_completo
        id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        telefono: telefono
        email: email
        rol: rol
      properties:
        id:
          format: uuid
          type: string
        email:
          type: string
        nombre_completo:
          type: string
        telefono:
          type: string
        descripcion:
          type: string
        rol:
          type: string
      type: object
    Direccion:
      example:
        etiqueta: etiqueta
        latitud: 6.027456183070403
        longitud: 1.4658129805029452
        direccion_texto: direccion_texto
        perfil_id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        id: 0
      properties:
        id:
          type: integer
        perfil_id:
          format: uuid
          type: string
        etiqueta:
          type: string
        direccion_texto:
          type: string
        latitud:
          type: number
        longitud:
          type: number
      type: object
    _auth_v1_token_post_request:
      properties:
        email:
          type: string
        password:
          type: string
      type: object
    _auth_v1_user_put_request:
      properties:
        password:
          type: string
      type: object
    _rest_v1_pedido_items_patch_request:
      properties:
        cantidad:
          type: integer
      type: object
    RegistroRequest_data:
      example:
        nombre_completo: Juan Perez
        direcciones:
        - etiqueta: Casa
          latitud: 0.8008281904610115
          longitud: 6.027456183070403
          direccion: "Colonia Centro, casa 10"
        - etiqueta: Casa
          latitud: 0.8008281904610115
          longitud: 6.027456183070403
          direccion: "Colonia Centro, casa 10"
        telefono: "99999999"
      properties:
        nombre_completo:
          example: Juan Perez
          type: string
        telefono:
          example: "99999999"
          type: string
        direcciones:
          items:
            $ref: '#/components/schemas/DireccionRegistro'
          type: array
      type: object
    AuthResponse_user:
      example:
        id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        email: email
      properties:
        id:
          format: uuid
          type: string
        email:
          type: string
      type: object
  securitySchemes:
    ApiKeyAuth:
      in: header
      name: apikey
      type: apiKey
    BearerAuth:
      bearerFormat: JWT
      scheme: bearer
      type: http

